### ISSUE TITLE
Add 2fas browser extension from Chrome Web Store

### ISSUE THREAD

**Issue by valorisa** [twofas/2fas-browser-extension#104]
### Feature description

Nobody here seems require this feature, so I ask it. 
![Screenshot_2024-10-11-09-02-22-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9da16cd7-6410-4f52-a90d-107507746bca)

### Motivation

Extension missing

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Hi @valorisa. Everything works, even from mobile phone, but only when your phone is connected to your Google Account and there is some desktop browser connected to the same account ;)

**Comment by valorisa** [comment]
Weird
![Screenshot_2024-10-11-11-02-32-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a8ba3216-d640-44a3-94e7-0cd6e17e829b)

**Comment by valorisa** [comment]
Thanks
