### ISSUE TITLE
feat: Populate clipboard on "Accept"

### ISSUE THREAD

**Issue by Etupa** [twofas/2fas-browser-extension#110]
### Feature description

Add an option to browser's extension so OS clipboard is automatically populated with generated code as soon as 2FAs "Accept" on external device. 

![image](https://github.com/user-attachments/assets/cbcc010d-db83-41fc-bf6f-ce27d8243c8f)

### Motivation

- Mainly remove 1 click to send OTP in clipboard,
- Useful for some non browser application that still need OTP.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Hi @Etupa. Thank you for your report. Unfortunately, we do not have the technical ability to do it. You can't automatically put something on the clipboard without the active focus on the window. That's why we require you to click the copy button.
