### ISSUE TITLE
fix auto input on firefox

### ISSUE THREAD

**Issue by Nixobe** [twofas/2fas-browser-extension#15]
it doesn't always work properly when i want to auto fill it with my phone (basically when i go eventually to the otp login section, and then i try to activate the extension, it tells me to reload the page, but it doesn't work)
<img width="1280" alt="firefox_P0dVshgCnH" src="https://github.com/twofas/2fas-browser-extension/assets/68926902/c9ded8fc-70f7-4f35-8641-1c4bae5acc18">

**Comment by GrzegorzZajac000** [comment]
I will check that. Could you turn on debug logs in browser extension settings and try logging in again?

**Comment by GrzegorzZajac000** [comment]
If there is any error, I will see it in our internal tools.

**Comment by GrzegorzZajac000** [comment]
@Nixobe Version 1.4.5 has just been uploaded to stores. Extension will be available for you in the coming days.
After updating the extension, please check if the error still occurs.
