### ISSUE TITLE
Code not auto-filling on specific website

### ISSUE THREAD

**Issue by hudcap** [twofas/2fas-browser-extension#16]
I get the push request and approve it, but nothing appears in the box. It works on other sites, so it seems to be an issue specifically with this site.
I'm comfortable with chrome devtools, so what information can I give you to help debug?

Thanks!

**Comment by GrzegorzZajac000** [comment]
Could you provide the url of these websites?

**Comment by GrzegorzZajac000** [comment]
Could you provide the url of these websites?

**Comment by hudcap** [comment]
https://login.nelnet.net/login

**Comment by GrzegorzZajac000** [comment]
Thanks. I will check that

**Comment by GrzegorzZajac000** [comment]
Unfortunately, I can't test logging in on this website because I can't create an account there :(

**Comment by hudcap** [comment]
Thanks for trying!
I figured you wouldn't be able to get to the mfa page—that's why I was offering to get data from the page for you.
Is there anything I could get that would help?

**Comment by GrzegorzZajac000** [comment]
This is a bit more complicated because I would need a full copy of the site with JS scripts.
Alternatively, is there any test account available for this website, or could you ask the website administrator for one?

**Comment by hudcap** [comment]
Unfortunately, I have no connections at this site...

**Comment by GrzegorzZajac000** [comment]
Okay. We will be releasing some fixes in version 1.4.5 soon. Maybe we can also fix the auto-fill on this website ;)

**Comment by hudcap** [comment]
Thank you! I hope so!
