### ISSUE TITLE
Error, after scanning the code from the browser, the application on Android crashes

### ISSUE THREAD

**Issue by snooppr** [twofas/2fas-browser-extension#17]
OS Android 9 (LOS)

Steps to reproduce the problem:
1. Install the 2FA extension for the Firefox browser (v117).
2. Open the extension, go to the Android 2FA mobile application (Settings -> Browser extension -> Pair witch...) and scan the QR code in the browser.
The application will start working and immediately crash with an error.
![Screenshot_20230909-104308_2FAS_Auth](https://github.com/twofas/2fas-browser-extension/assets/61022210/4a7b3144-0ba5-4091-a1c8-90876db09f0a)
Then the application crashes.

**Comment by starscream00** [comment]
I have the same issue, the android app crash immediately after pressing the pair button. Need a fix asap !
