### ISSUE TITLE
[Feature request] Hide context menu item

### ISSUE THREAD

**Issue by Trixlight** [twofas/2fas-browser-extension#18]
Context menus are very large nowadays, and when each extension tries to add its own item to it, it can sometimes become a real mess. So it will be great if we can hide it.

**Comment by GrzegorzZajac000** [comment]
Thank you for reporting this suggestion.
We will introduce this option in version 1.4.5 ;)

**Comment by GrzegorzZajac000** [comment]
@Trixlight Version 1.4.5 has just been uploaded to stores.
Depending on your browser, the plugin will be available for you in the coming days.
Stay tuned ;)
