### ISSUE TITLE
Infinite Loading after fresh install 

### ISSUE THREAD

**Issue by ShinP451** [twofas/2fas-browser-extension#21]
### System Details

OS: Windows 11
Chromium version 118.0.5993.89

### Problem
Hello, after install 2fas you get an infinite Loading screen on the installPage.html 

### Reproduce

install fresh chromium 

install 2fas extension from chromewebstore

after install the extension you get infinite Loading and nothing happens

**Comment by GrzegorzZajac000** [comment]
Thanks. We already know about this issue, and it will be fixed in v1.4.6.

**Comment by GrzegorzZajac000** [comment]
Version 1.4.6 was uploaded to stores. It should be public available in few hours.
