### ISSUE TITLE
Extension storage is corrupted

### ISSUE THREAD

**Issue by eugenioperea** [twofas/2fas-browser-extension#23]
This error appears when installing the browser extension on Chromium.

![Screenshot from 2023-11-06 13-26-55](https://github.com/twofas/2fas-browser-extension/assets/84279757/54f5dc52-ef47-4710-91b6-8a8daa0ae7ba)

Browser is vanilla Chromium. OS is Ubuntu Linux. 

I've attempted installation several times, to no avail. I've also disabled other extensions, to see if they interfere, but that doesn't work, either. 

This is not ungoogled-chromium, it's just normal Chromium.

**Comment by GrzegorzZajac000** [comment]
Thanks. We already know about this issue, and it will be fixed in v1.4.6.

**Comment by GrzegorzZajac000** [comment]
Version 1.4.6 was uploaded to stores. It should be public available in few hours.
