### ISSUE TITLE
Firefox browser extension posting incorrect 2FA tokens from Android

### ISSUE THREAD

**Issue by eennoo** [twofas/2fas-browser-extension#3]
2fas Android app version: 4.5.0
Browser extension version: 1.4.2
Android 13, latest security update, Pixel 6
MacOS: 12.6.5
Firefox version: 112.0.1

After the last update of the 2fas Android application, when using the browser extension to fill out tokens automatically, the tokens that gets filled out (after authentication with fingerprint and tapping 'approve' in the Android app), are scrambled, posting 9 characters with the numbers from the 6 digit token in random order.

I suspect something with the latest Android update broke something in the Android-Browser connection.

**Comment by rafakob** [comment]
Thanks, I will check that. Could you tell me on which website are you trying to log in?

**Comment by eennoo** [comment]
Any website.

I just discovered when it happens.

If I click on the notification and select the site manually in your app, then it works. If I however use the quick action in the Android notification and click on 'Approve' and where 2FAS automatically identifies the site and  sending the token codes to my browser, that is when it happens.

**Comment by eennoo** [comment]
This seems to have been fixed with the latest version of your app. 4.5.5
