### ISSUE TITLE
Not filling in token or when it does it only adds the last number

### ISSUE THREAD

**Issue by gcstang** [twofas/2fas-browser-extension#30]
QNAP NAS 2 factory login, multiple accounts for this page but only using one
Chrome Version 119.0.6045.199 (Official Build) (arm64)
Android Pixel 8 Pro running Android 14 with latest January 2024 Patch
2FAS Version Android version 5.2.0
2FAS Browser Plugin: Version  1.5.0

After authorizing on the phone the desktop just say's an error happened.

**Comment by Tipoff4317** [comment]
Yes, I have the same problem on securityscorecard.
FF browser extension: 1.5.0
Android app: 5.2.0

1. Try to login
2. When 2FA code field appear, click on the extension
3. Approve on device
4. You see a single digit appearing, one by one, apparently replacing the prior digit entered.

**Comment by GrzegorzZajac000** [comment]
@gcstang @Tipoff4317 Thank you for reporting these bugs.
@gcstang We will test it, but we need to find some QNAP device.
@Tipoff4317 I confirm that this bug exists. We will try to fix it in version 1.6.0.

**Comment by GrzegorzZajac000** [comment]
@gcstang @Tipoff4317 Version 1.6.0 has been uploaded to stores. It should be visible to users in the next few hours. Feel free to share whether your problems has been fixed ;)

**Comment by Tipoff4317** [comment]
@GrzegorzZajac000 

> Feel free to share whether your problems has been fixed ;)

Thanks for the fix!  Confirmed fixed for securityscorecard.io, FF extension 1.6.0, and Android 5.2.0.
