### ISSUE TITLE
Ability to add service from the browser

### ISSUE THREAD

**Issue by csm10495** [twofas/2fas-browser-extension#33]
Hey folks,

It would be really useful if I could add a service from the browser extension.

It could be done as a one time thing where it tries to push it to the app and the app asks 'do you want to add X from Y?' If you click yes, the app will then have the service, etc.

**Comment by 2fas-com** [comment]
Thank you for your suggestion, we appreciate it and will consider it.
However, we cannot currently guarantee if or when it will be implemented.
