### ISSUE TITLE
Extension slowing down sites

### ISSUE THREAD

**Issue by Christophe999s** [twofas/2fas-browser-extension#38]
Extension causes sites to take 100% CPU.
Using MacBook Air M1, tested with both Waterfox and Brave.
Disabling the extension solves the problem.
With extension enabled, the page does not continue
<img width="1654" alt="Screenshot 2024-01-27 at 22 14 08" src="https://github.com/twofas/2fas-browser-extension/assets/36367001/d42bb924-42f4-4945-83fe-6bc5ac3ce0e1">
![Screenshot 2024-01-27 at 22 14 33](https://github.com/twofas/2fas-browser-extension/assets/36367001/361dc663-9f80-439b-ae33-ca8c7221a335)
With the extension disabled, page loads immediately
<img width="1148" alt="Screenshot 2024-01-27 at 22 16 08" src="https://github.com/twofas/2fas-browser-extension/assets/36367001/8d333d68-8fc6-4048-8811-6d5c1a743ede">

**Comment by claabs** [comment]
I'm also seeing this on several sites on Firefox 122. [Here's](https://streamelements.com/hitsquadgodfather/store) a random public site that experiences it.

I ran the profiler, and here's the stack trace of some code that gets 60% of the hits:
```
o [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24708]
./src/content/observer/observerFunctions/checkChildNodes.js/o/< [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24765]
map [self-hosted:221:18]
o [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24708]
./src/content/observer/observerFunctions/checkChildNodes.js/o/< [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24765]
map [self-hosted:221:18]
o [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24708]
./src/content/observer/observerFunctions/addedNodes.js/e.exports/< [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24251]
map [self-hosted:221:18]
./src/content/observer/observerFunctions/addedNodes.js/e.exports [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:24188]
./src/content/observer/createObserver.js/e.exports/</< [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:22528]
forEach [self-hosted:203:22]
./src/content/observer/createObserver.js/e.exports/< [Extension "2FAS - Two Factor Authentication" (ID: admin@2fas.com): moz-extension://a7ae6c4b-9c0a-4c6e-9535-1cf4b9aa1e69/content/content_script.js:1:22498]
MutationCallback
```

For now, I'm just disabling the extension.

**Comment by cshafer2** [comment]
I'm seeing a similar slow down with dramatically increased loading times for my locally hosted Omada SDN controller. Loading times go back to normal after disabling the extension.

**Comment by ScottESanDiego** [comment]
I see that, and also some sites fail to load completely.  E.g., the eBay "sell an item" page where you make a new listing.  With 2FAS extension enabled it fails to completely load (Chrome shows the "X" icon not the "Reload" icon, and you can't change things like dropdown menu items on the page).  Unclear if this is a side-effect of the CPU usage, or not.

**Comment by GrzegorzZajac000** [comment]
Sorry for the inconvenience. I'm already working on a fix

**Comment by GrzegorzZajac000** [comment]
I have just submitted version 1.6.1 for testing. If everything goes smoothly, the new version will be sent to extension stores within a few hours.

**Comment by Kiyo5hi** [comment]
I faced the same issue these few days. It takes forever to load Jupyter Lab. After disabling the extension, the page is loaded without issue.

**Comment by GrzegorzZajac000** [comment]
v1.6.0 has been uploaded to stores. It should be visible in the next few hours.

**Comment by Christophe999s** [comment]
Thank you, just got the update and everything seems ok now!

**Comment by MagsMagnoli** [comment]
@GrzegorzZajac000 I'm on 1.6.1 and sadly still see the issue. Oddly it doesn't happen when I directly visit the page in question but when navigating to it via anchor tag.

Check it out:
- visit: https://nadcl.mags.gg/events/vqb7btlrptckj7kayslubpy9
- click 'players' and the site takes like 10s to load
- open a new tab and visit the players page directly and its fast: https://nadcl.mags.gg/events/vqb7btlrptckj7kayslubpy9/players

![Screenshot 2024-01-31 at 12 26 27](https://github.com/twofas/2fas-browser-extension/assets/4146037/d370abac-eb59-47b8-a389-f06c0cdf5e3f)

![Screenshot 2024-01-31 at 12 25 05](https://github.com/twofas/2fas-browser-extension/assets/4146037/02afaaa0-8ff5-4cee-a11f-7bad5c198f32)

**Comment by ScottESanDiego** [comment]
Good find @MagsMagnoli .  I see the same behaviour on Chrome/Windows.

**Comment by aaron3238** [comment]
> @GrzegorzZajac000 I'm on 1.6.1 (Firefox) and sadly still see the issue. Oddly it doesn't happen when I directly visit the page in question but when navigating to it via anchor tag.
> 
> Check it out:
> 
> * visit: https://nadcl.mags.gg/events/vqb7btlrptckj7kayslubpy9
> * click 'players' and the site hangs
> * open a new tab and visit the players page directly and its fast: https://nadcl.mags.gg/events/vqb7btlrptckj7kayslubpy9/players
> 
> ![Screenshot 2024-01-31 at 12 26 27](https://private-user-images.githubusercontent.com/4146037/301251543-d370abac-eb59-47b8-a389-f06c0cdf5e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjMsIm5iZiI6MTcwNjcyMjUyMywicGF0aCI6Ii80MTQ2MDM3LzMwMTI1MTU0My1kMzcwYWJhYy1lYjU5LTQ3YjgtYTM4OS1mMDZjMGNkZjVlM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjYzc2YTFmMWRhZDlkNTE5ZGRiMGY2OTAxNmUwNWMzMjA3NWIyZGIwYTkzNjE2M2YzNDQxN2Q4MTlkYzM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8jrt_g-tR_pL6dVNt_9nq-CMM9zWhMKkOUzfFbka_uw)
> 
> ![Screenshot 2024-01-31 at 12 25 05](https://private-user-images.githubusercontent.com/4146037/301251618-02afaaa0-8ff5-4cee-a11f-7bad5c198f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjMsIm5iZiI6MTcwNjcyMjUyMywicGF0aCI6Ii80MTQ2MDM3LzMwMTI1MTYxOC0wMmFmYWFhMC04ZmY1LTRjZWUtYTExZi03YmFkNWMxOThmMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg1MTA0M2JjZTQ2NmEzZWQwZjljYjUxZTEzYmYzYzI2MGU0MTViMmJjM2ZiMTJjOWQyZDQ0OTUyOTM3YmMyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.S1a_S7R7ZBBAA55uDca7bVxHbk5vPgBjYr6j26xq_To)

Can replicate same behavior on vivaldi. Loads fine via anchor tag with extension disabled. Tried testing this with other sites that load large amounts of data in one go and I've had inconsistent results. Will try some others.

**Comment by GrzegorzZajac000** [comment]
@MagsMagnoli @ScottESanDiego @aaron3238 Thanks for testing. I'll check it

**Comment by GrzegorzZajac000** [comment]
Sorry for slight delay, but we had few another problems. v1.6.2 was uploaded to stores. Should be available in near future for users. Thank you for patience ;)
