### ISSUE TITLE
Autofilling for community.bitwarden.com, forum.torproject.org (discourse?)

### ISSUE THREAD

**Issue by Tipoff4317** [twofas/2fas-browser-extension#42]
### Description

Autofilling on the community.bitwarden.com, forum.torjproject.org recycles back to the login page.

### Steps to reproduce:

1) community.bitwarden.com (or forum.torproject.org)
2) hit Login
3) Enter email and password
4) On the 2FA page, hit the 2FAS button
5) Approve on the phone
6) All 6 digits filled in, and _without_ having to hit the "Login" button, the page recycles back to the front page without having logged in

Entering the code manually, _having to_ hit the Login button on the page, will login properly.

This is probably related to the Discourse servers.

### Platforms:

Windows Pro 11
FF 115.7.0esr (x64 bit)
2FAS FF browser extension: 1.6.1
Android 2FAS: 5.2.0

### Comments

Having to get this to work with all the websites is probably a freaking pain.  It's a really nice feature, though, and is one of the reasons I use 2FAS instead of Aegis.

**Comment by GrzegorzZajac000** [comment]
I will check these sites, but also you can disable auto submit for problematic websites in extension's options.

**Comment by GrzegorzZajac000** [comment]
Unfortunately, I tried my best, but I can't fix that problem.
I followed how TOTP works in Discourse and created a [topic in their community](https://meta.discourse.org/t/totp-modal-problem-cooperation-with-2fas-browser-extension/293760) in which I suggested what changes they should make. If they enter them, you will also have to wait until the administrators of individual pages update the script version.

For now, you can only exclude these domains from auto submit feature.

**Comment by Tipoff4317** [comment]
Thanks for looking into it.   The extension is a brilliant feature that makes life easier!

**Comment by GrzegorzZajac000** [comment]
@Tipoff4317 I'm in contact with someone from Discourse, but for now I did a trick that makes the problem no longer occur. v1.6.2 was uploaded to stores. Should be available in near future ;)

**Comment by Tipoff4317** [comment]
@GrzegorzZajac000, you are pretty awesome to go that far.  Wow.

Thank you!

**Comment by Tipoff4317** [comment]
Yeah, confirmed fixed on all the discourse sites I have accounts on.
