### ISSUE TITLE
Cannot Fill Codes on AWS Console

### ISSUE THREAD

**Issue by brandoningli** [twofas/2fas-browser-extension#45]
Similar to #35 , I'm getting the same error on the AWS console (signin.aws.amazon.com). I'm prompted to select the text field first despite having the field selected.

Firefox 122.0.1 on macOS
2FAS extension version 1.6.2

**Comment by GrzegorzZajac000** [comment]
@brandoningli Thank you for reporting this bug. I will check that.

**Comment by GrzegorzZajac000** [comment]
@brandoningli Unfortunately I cannot confirm this issue. I tested logging into AWS on Chrome and Firefox, both on Windows and MacOS, and each time the input was detected correctly.

**Comment by brandoningli** [comment]
This occurred again for me just now, same Firefox and Extension versions.

**Comment by GrzegorzZajac000** [comment]
@brandoningli Fix for GitHub may also work for you on AWS, but it's hard for me to test it because this bug doesn't occur for me.
One more question. Are you using a VPN?

**Comment by brandoningli** [comment]
I'm not using a VPN.

**Comment by jetofisher** [comment]
I'm also experiencing this with AWS and another site when using Firefox (v122.0.1). 
These sites are working in Brave Browser (v1.62.165) when I test there.
No VPN.
2FAS v1.6.2

**Comment by GrzegorzZajac000** [comment]
Can you give me some URL? Maybe there is some different login forms

**Comment by cotman** [comment]
New user to 2FAS from Authy, and I have the same problem on all my AWS sites and the browser extension.

![aws_fail_20240219](https://github.com/twofas/2fas-browser-extension/assets/2264867/995f40ec-7656-46a7-9781-6236d6dfa583)

**Comment by GrzegorzZajac000** [comment]
@cotman Can you send me a screenshot of DOM element of this input from developer console?

**Comment by cotman** [comment]
Not entirely sure if this is what you're after, but this is the element in Chrome DevTools: 
![aws_console_mfa_input_1](https://github.com/twofas/2fas-browser-extension/assets/2264867/5b7472cf-8f82-4ea2-8414-455ef298531c)

**Comment by cotman** [comment]
Excellent - thanks @GrzegorzZajac000

**Comment by jetofisher** [comment]
Hey @GrzegorzZajac000,

The URL I have is a work one and you'd need an account to expose the 2FA input. 
Here is the HTML element if it helps?

<div class="p-field p-col-12">
	<label for="challenge" data-bt="challengeText" class="challenge-text">Your user account requires two factor
		authentication. Enter the six-digit code generated by your authenticator app.</label>
	<input name="challenge" type="password" value="" id="challenge" data-bt="challenge" autofocus=""
		autocomplete="new-password" data-lpignore="true" class="p-inputtext p-component" spellcheck="false">
</div>

**Comment by GrzegorzZajac000** [comment]
@jetofisher That is another input, but this time with password type... Oh, man. I will add this case too. Thank you

**Comment by jetofisher** [comment]
Appreciate you @GrzegorzZajac000! :)

**Comment by GrzegorzZajac000** [comment]
v1.6.3 was uploaded to stores. Should be available in next hours.

**Comment by brandoningli** [comment]
Just got 1.6.3, and happy to report the AWS code is being filled properly again! Closing this issue out with that news.

**Comment by Tech323x** [comment]
> @Tech323x it is best to open a new bug report.

Done.  Thanks for your help!
