### ISSUE TITLE
Firefox extension works so, so on GitHub

### ISSUE THREAD

**Issue by ncdaol** [twofas/2fas-browser-extension#46]
After GitHub shows the input for the TOTP, sending a request to the mobile app doesn't do anything. I have to reload the page for it to work.

Firefox 122.0.1 on macOS
2FAS extension version 1.6.2

Additional information: I use passkey as default, so I have to manually select to use authenticator app.

**Comment by GrzegorzZajac000** [comment]
@ncdaol Confirmed, I found an error. Will be fixed in version 1.6.3

**Comment by eriktdesign** [comment]
Just wanted to chime in that the Chrome extension also does not like github -- not sure if it's the same issue as @ncdaol has experienced. If I get to the 2fa page and click either the toolbar button or select 2fas from the context menu, it doesn't recognize that I have the 2fa field focused.

**Comment by GrzegorzZajac000** [comment]
@eriktdesign Yes, it will be the same error.

**Comment by GrzegorzZajac000** [comment]
v1.6.3 was uploaded to stores. Should be available in next hours.
