### ISSUE TITLE
Browser extension won't pass code to Crowdstrike site

### ISSUE THREAD

**Issue by smoke007** [twofas/2fas-browser-extension#47]
Hello,
I've used the Browser Extension Check to confirm my browser extension works.  However, on Crowdstrike's site, nothing happens after I approve the request on my phone.  After reading over closed issues for other sites where the extension didn't work, I'm guessing Crowdstrike has done something to make this difficult to be compatible?  

The URL of the 2fa is https://falcon.us-2.crowdstrike.com/login/
Since you have to be a paying customer to be able to login here, I don't know how easily this will be able to be investigated this.  

When I bring up the Dev tools on the page and inspect the elements, I can see 6 warnings:
A form field element should have an id or name attribute
A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

They broke up the 2fa field into 6 separate boxes for the 6 digits.  When you type in the first number, it auto moves to the next field so I can type or paste the 6 digit code on the page just fine.

When I view the first warning, it takes me to this element, which is the first of six boxes:
`<input class="focus:outline-none m-1 h-8 w-7 flex-grow rounded-sm bg-overlay-1 p-1 text-center shadow-focusable-outline focus-within:shadow-focus-outline
          
          " data-segment-index="0" aria-label="First digit of the 6-digit verification code" maxlength="2">`
		  
The JS path is:
`document.querySelector("body > div.flex.min-h-screen.flex-col.leading-none.text-body-and-labels.min-w-toucan.bg-ground-floor > div > div.glow.mx-auto.mt-16.rounded.border.border-solid.border-lines-dark.p-8 > div.max-w-2xl > form > div.flex.flex-row.items-center.justify-center > div:nth-child(1) > input")`

Hope this helps, otherwise please let me know if I can help to provide better info.  Also, there is good public support for Crowdstrike here, if a Dev wanted to try and ask CS support for info to try and make this compatible, but no idea if they'd offer help really?  :)  https://www.reddit.com/r/crowdstrike

Thank you for your time.  :)

**Comment by GrzegorzZajac000** [comment]
@smoke007 Thank you for such detailed information. Input element doesn't have any type on it (f.e. text / number...). In 1.6.2 and earlier versions of this extension I ignored inputs like this, but I changed it in 1.6.3. It should be fixed with new version ;)

**Comment by smoke007** [comment]
@GrzegorzZajac000  Thank you so much for the quick response, wow!  I'll keep an eye out for the 1.6.3 update and report back after testing.  Thanks!!

**Comment by smoke007** [comment]
When should I be able to see version 1.6.3 extension in the Add-on store?  Is there a regular schedule for updates to get pushed to PROD?  Thanks!  https://microsoftedge.microsoft.com/addons/detail/2fas-two-factor-authent/dpaelbjipneennmjbjmgkdlbajncmbmj

**Comment by GrzegorzZajac000** [comment]
@smoke007 v1.6.3 is under our internal testing. I'll let you know when we put this version in stores, but Microsoft usually acceptes the new version after 7 business days :(

**Comment by GrzegorzZajac000** [comment]
v1.6.3 was uploaded to stores. Should be available in next hours.
