### ISSUE TITLE
Does not populate Authelia Codes fully

### ISSUE THREAD

**Issue by thering1975TG** [twofas/2fas-browser-extension#48]
When visiting my sites that i protect with Authelia, the first digit is always lost so when it populates the code there are only 5 digits entered with the first digit from the app being lost. The 2nd digit on the app becomes the first digit on the browser page thus the last digit i.e number 6 on the web page is blank

This is between a s21Ultra and a webpage accessed on latest Edge browser and latest extension

**Comment by GrzegorzZajac000** [comment]
@thering1975TG Can you share with me at least one of these sites which is public?

**Comment by GrzegorzZajac000** [comment]
I'm closing the issue due to lack of information. As soon as I get the data I need, I will come back to the problem.
