### ISSUE TITLE
OneLogin text field not recognized 

### ISSUE THREAD

**Issue by ItielOlenick** [twofas/2fas-browser-extension#50]
<img width="774" alt="Screenshot 2024-02-19 at 10 07 38" src="https://github.com/twofas/2fas-browser-extension/assets/67790309/60d933ed-4262-4951-9501-9370faf1a486">

2FAS Version 1.6.2
MAC - Chrome Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by ItielOlenick** [comment]
Perhaps it would be a good idea to create a section in the web extension with all of the registered services tokens

**Comment by GrzegorzZajac000** [comment]
@ItielOlenick We know that bug. Will be fixed in v1.6.3.

**Comment by GrzegorzZajac000** [comment]
v1.6.3 was uploaded to stores. Should be available in next hours.

**Comment by hudcap** [comment]
Just had this happen on a different site, found this issue, manually updated, and voila! It worked.
Thank you!
