### ISSUE TITLE
MFA code text field not recognized on NextDNS login page

### ISSUE THREAD

**Issue by PSalant726** [twofas/2fas-browser-extension#51]
Previously the extension recognized the MFA text field that appears after entering the username/passowrd on https://my.nextdns.io/login. A recent extension update has regressed this behavior, such that the field is no longer recognized and the following notification is displayed:

<img width="386" alt="Screenshot 2024-02-20 at 12 12 33 PM" src="https://github.com/twofas/2fas-browser-extension/assets/18120121/20609f5c-0cd3-4443-92e9-1091e923abc8">

**Comment by GrzegorzZajac000** [comment]
@PSalant726 We know that bug. Will be fixed in v1.6.3.

**Comment by GrzegorzZajac000** [comment]
v1.6.3 was uploaded to stores. Should be available in next hours.

**Comment by PSalant726** [comment]
Confirming that v1.6.3 resolves this issue. Thanks!
