### ISSUE TITLE
Can't register new local user

### ISSUE THREAD

**Issue by emptyfist** [twofas/2fas-browser-extension#7]
I used 2FA google chrome extension before and after changing the PC and tried to register a new local user but can't register new user.
"Registering user..." screen didn't change at all.
What's the problem?
![image](https://github.com/twofas/2fas-browser-extension/assets/90226717/4d6a5ea5-87a9-4f07-a5be-3f75887c351d)

PS: Chrome info
![image](https://github.com/twofas/2fas-browser-extension/assets/90226717/02f52a8e-d20b-49b5-82ae-5111fa383c2d)

**Comment by GrzegorzZajac000** [comment]
Hi!
Thank you for your message.
However, this is not our Browser extension. If you'd like to use anonymous and private browser extension, please go to [https://2fas.com/be](https://2fas.com/be).
In other case, please get in touch with appropriate developer.
