### ISSUE TITLE
feat:  Application for Windows

### ISSUE THREAD

**Issue by MaximusPanin** [twofas/2fas-browser-extension#70]
### Feature description

![8034566](https://github.com/twofas/2fas-browser-extension/assets/24373505/2c9740cb-2b3b-4c7e-a0c9-0b46b9497062)

Recently it became known that the popular cross-platform application **Authy** [will no longer be updated for Windows](https://help.twilio.com/articles/22771146070299-User-guide-End-of-Life-EOL-for-Twilio-Authy-Desktop-app).
End-of-Life on **March 19, 2024**. There is a good opportunity to occupy this segment. How do you like it ? (plugins for Chrome are not considered).

### Motivation

There are no cross-platform products left among 2FA programs.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@MaximusPanin We don't have desktop app and for now, we do not plan to implement it. Check #69 for more informations
