### ISSUE TITLE
feat: Support multiple 2fas for one domain with a white list 

### ISSUE THREAD

**Issue by akrohn** [twofas/2fas-browser-extension#72]
### Feature description

On sites like Kraken you have multiple 2fas for different services, like one for sign in and another for trading. 

At the moment the browser extension doesn't help because you can't differantiate between the two Kraken 2fas. 

With a white list you could set a domain like https://pro.kraken.com/app/* for using the Kraken trading 2fa and https://pro.kraken.com/signin/* for Kraken sign in 2fa.

Regarding security reasons I would also suggest activating the auto submit feature only on domains that are on a white list.

### Motivation

A white list will raise the security level of the browser extension and it will support even websites that use multiple 2fas.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@akrohn Thank you for your contribution, and we apologize for the inconvenience.
Changing domain support would involve modifications on the Browser Extension, mobile applications and probably API. Currently, we have other priorities, but I'll save this idea and come back to it in the future.
For now, we do not plan to implement any whitelist mechanism and auto submit feature was causing too much trouble at the moment so we decided to change it status to Experimental.
