### ISSUE TITLE
bug: Cannot Fill Codes on Canary Console Similar to #35 and #45

### ISSUE THREAD

**Issue by Tech323x** [twofas/2fas-browser-extension#75]
### Browser info

Chrome (Window and Mac)

On Mac: Version 122.0.6261.129 (Official Build) (arm64)

### Browser extension version

1.6.4

### Website

My login page at: canary.tools

### Bug description

Similar to #35 & #45 , I'm getting the same error on my Canary Console login page (canary.tools). I'm prompted to select the text field first, despite having the field selected.

I have included a snip of the HTML for more information

![Canary tools](https://github.com/twofas/2fas-browser-extension/assets/164199943/71d532ba-0e12-4c47-8aa8-a5e3494a0662)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Tech323x** [comment]
I have included a snip of the HTML for more information

**Comment by GrzegorzZajac000** [comment]
@Tech323x I'm working on a new mechanism that will appear in 1.7.0. Should fix this bug ;)

**Comment by GrzegorzZajac000** [comment]
v1.7.0 was uploaded to stores. Should be available in next hours.

**Comment by Tech323x** [comment]
> v1.7.0 was uploaded to stores. Should be available in next hours.

That fixed it.

Thanks!
