### ISSUE TITLE
bug: dbrand.com website not loading properly with 2FAS enabled

### ISSUE THREAD

**Issue by plasticrake** [twofas/2fas-browser-extension#76]
### Browser info

Chrome (MacOS) 123.0.6312.87 (Official Build) (arm64)

### Browser extension version

1.6.4

### Website

https://dbrand.com/shop/grip/steam-deck-cases

### Bug description

The "Step 1: Choose your Customization" picker does not load the options when 2FAS is enabled.
2FAS Enabled:
<img width="1197" alt="Screenshot 2024-03-29 at 4 59 46 PM" src="https://github.com/twofas/2fas-browser-extension/assets/1383980/7fd9ded0-c59e-49e6-97d3-8e7a2ad4f0c3">
2FAS Disabled:
<img width="1197" alt="Screenshot 2024-03-29 at 4 59 57 PM" src="https://github.com/twofas/2fas-browser-extension/assets/1383980/e31470c4-cb99-4540-8548-a519e6f66c9c">

### Solution

Disable 2FAS

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@plasticrake I'm working on a new mechanism that will appear in 1.7.0. Should fix this bug ;)

**Comment by GrzegorzZajac000** [comment]
@plasticrake This should be fixed in v1.7.0

**Comment by GrzegorzZajac000** [comment]
v1.7.0 was uploaded to stores. Should be available in next hours.
