### ISSUE TITLE
bug: "Select text field first" on Lottoland.com / 2FA code is not transmitted

### ISSUE THREAD

**Issue by lantura** [twofas/2fas-browser-extension#77]
### Browser info

Brave Version 1.64.113 Chromium: 123.0.6312.86 (Offizieller Build) (64-Bit)

### Browser extension version

1.6.4

### Website

https://www.lottoland.com/

### Bug description

I enter the 2FA text code field, right mouse click, choose  "Send a request to 2FAS" I receive the following message:
"Select the text field first. 
Select the text field for the 2FA token then click the extension icon or use the chosen shortcut".
I have to enter the 2FA code manually.
Click on extension icon and shortcut don't work either.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@lantura I'm working on a new mechanism that will appear in 1.7.0. Should fix this bug ;)

**Comment by GrzegorzZajac000** [comment]
v1.7.0 was uploaded to stores. Should be available in next hours.
