### ISSUE TITLE
bug: error 3 on recreated token when requesting it from phone

### ISSUE THREAD

**Issue by evidenz** [twofas/2fas-browser-extension#87]
### Browser info

Firefox (macOS) 128.0

### Browser extension version

1.7.0

### Website

https://paypal.com

### Bug description

﻿I cannot provide back the token after a request. I receive the error `Error while sending the code. The operation couldn't be completed. (TwoFAS.AuthRequestsModuleInteractorError error3.).

![Screenshot 2024-07-12 at 10 37 51](https://github.com/user-attachments/assets/72bcb6c7-e3cf-4fa7-a22f-9d9fdd1e2c9b)

It is a re-created token, however other re-created ones work just fine - it does not work for the Paypal website, it did work before though.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Thank you, @evidenz, for your feedback. I confirmed that such a bug occurs in the mobile application. I'm adding our iOS devs to this issue.

**Comment by GrzegorzZajac000** [comment]
@evidenz I received information from our iOS devs that the bug has been fixed ;)
