### ISSUE TITLE
feat: Add an option for showing codes directly on the browser on PC without the mobile being turned on

### ISSUE THREAD

**Issue by Ahmed-Soudi** [twofas/2fas-browser-extension#88]
### Feature description

I would like to have an option to show the codes directly on Chrome. I know It's a risk, but it's a feature that I want nonetheless.

### Motivation

I want that feature for easy of access on all websites, even websites that have 2FA as a mandatory requirement. I don't to have to reach for the phone every single time 2FA is required.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@Ahmed-Soudi We don't plan to implement this at the moment, but it's possible that we'll change the extension's behavior in the future.
