### ISSUE TITLE
feat: Firefox easier method to access to settings page

### ISSUE THREAD

**Issue by codejnki** [twofas/2fas-browser-extension#92]
### Feature description

Please consider adding a slightly easier method to accessing the browser extension settings in Firefox.  

Accessing the settings page in Firefox is a bit confusing, especially as a brand new user.  To reach the settings you must follow these steps:

* Right click on browser icon
* Select "Manage Extension" (This takes you to the Add-ons Manager in Firefox)
* Find the triple dot icon next to the Enable/Disable switch
* Select Options from this sub menu

![image](https://github.com/user-attachments/assets/c5ce6c04-43c0-4240-aa53-2e0e18ab22b8)

### Motivation

I am a brand new 2FAS user and it took me between 10 and 20 minutes to figure out how to find the browser extension settings again.  The natural instinct is to click on the browser icon to hopefully get a menu, but this only results in a push notice to my phone.

I can understand the desire to try and keep this interaction as simple and straightforward as possible, but if there's a creative idea to surface the settings page it would help new users adopt the plugin.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Thank you @codejnki for this suggestion. I will try to implement it in next version ;)
