### ISSUE TITLE
feat: Approval from apple watch for browser extention

### ISSUE THREAD

**Issue by Cl8vM1nd** [twofas/2fas-browser-extension#96]
### Feature description

I would like to be able to approve request from browser extension, without the need to open my phone.
This would help significantly in speeding up the whole usage.
Currently if I click on notification on my watch it just opens for me an app.
I think the flow should be: when you request token from the browser and click on notification on watch, there is a button like approve or not and if you hit approve you will see the token in the browser. This will be game changing!

### Motivation

You will provide an ability to get approval from watch without the need to unlock and touch the phone all the time. This will safe tons of time.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@Cl8vM1nd Thanks for your report, but unfortunately I can't do this on browser extension. Please submit this feature on [Android](https://github.com/twofas/2fas-android) or [iOS](https://github.com/twofas/2fas-ios) repo.
