### ISSUE TITLE
feat: Allow alternate icon colors

### ISSUE THREAD

**Issue by cherealnice** [twofas/2fas-browser-extension#97]
### Feature description

Allow users to set alternate icons for 2fas browser extension to avoid conflict with other browser extensions. This could be a collection of different colors, or alternate icon(s) that invert the colors of the existing. This is specifically for Chrome, but probably applies to other browsers (I noticed there are different icons for safari)

### Motivation

I currently use the 2fas browser extension and I also use the gmail checker plus browser extension. Since they both use a very similar red color, I have several times thought that I have an unread email when I actually just see the 2fas icon out of the corner of my eye. It would be great to allow users to select alternate icons to avoid conflicts with other browser extensions (I'm opening a similar request with the gmail extension). I know it seems like a minor issue, but it is a bit mentally taxing to be thrown out of concentration several times per day.

It's understandable if there's a need to be consistent with colors for branding purposes, so if it's not acceptable to offer alternate colors, even offering some kind of inverted icon would be a huge win.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
@cherealnice v1.7.3 was uploaded to stores. Feature should be available in next hours ;)

**Comment by cherealnice** [comment]
Amazing @GrzegorzZajac000. Thank you!
