### ISSUE TITLE
bug: Notification layout broken/ buttons inaccessible

### ISSUE THREAD

**Issue by ccornici** [twofas/2fas-browser-extension#98]
### Browser info

Version 127.0.6533.122 (Official Build) (64-bit)
Windows 10
Screen rez: 1920x1080 scaled to 125%

### Browser extension version

1.7.2

### Bug description

Install extension
Click on it to open it
See screenshot in this post.

### Additional context

![image](https://github.com/user-attachments/assets/1312e856-8269-4e9e-be63-6464d15e291b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Hi @ccornici. I tested this issue and this problem occurs only on a specific websites. Can you send me URL where you tested this case?

**Comment by ccornici** [comment]
@GrzegorzZajac000 IIRC it was on the Microsoft login page, such as https://login.microsoftonline.com/

**Comment by GrzegorzZajac000** [comment]
> @GrzegorzZajac000 IIRC it was on the Microsoft login page, such as https://login.microsoftonline.com/

Jackpot! Thank you. It will be fixed in the next version ;)
